version: 0.2

env:
  parameter-store:
    CurrentEnvironment: CurrentEnv

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo change gradlew permissions... `date`
      - chmod +x gradlew
  build:
    commands:
      - echo build started on `date`
      - ./gradlew clean buildZip
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/distributions/java-boot-simple-service-starter.zip
  discard-paths: yes